const qs=new URLSearchParams(location.search),memorialId=qs.get("id"),slug=qs.get("slug");let memorial=null,memories=[],reviewIndex=0;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(){let q=sb.from("memorials").select("*").eq("published",true);if(memorialId)q=q.eq("id",memorialId);else if(slug)q=q.eq("slug",slug);else{document.getElementById("storyName").textContent="Memorial not found";return}const m=await q.maybeSingle();if(m.error||!m.data)return;memorial=m.data;document.title=(memorial.full_name||"Life Story")+" — CrowRules Memorials";storyName.textContent=memorial.full_name||"A Life Remembered";storyDates.textContent=[memorial.birth_date,memorial.passing_date].filter(Boolean).join(" — ");storyBio.textContent=memorial.short_bio||memorial.known_for||"Every life has a story.";const storyHero=document.querySelector(".story-hero");if(storyHero&&memorial.portrait_url){storyHero.style.backgroundImage="linear-gradient(90deg,rgba(10,10,10,.95),rgba(10,10,10,.65)),url(\""+memorial.portrait_url.replace(/"/g,"&quot;")+"\")";storyHero.style.backgroundSize="cover";storyHero.style.backgroundPosition="center";}const id=memorial.id;
const [p,s,t,e]=await Promise.all([sb.from("memorial_photos").select("id,caption,image_url,storage_path,created_at").eq("memorial_id",id).eq("published",true).order("created_at"),sb.from("memorial_stories").select("id,title,story,created_at").eq("memorial_id",id).eq("published",true).order("created_at"),sb.from("memorial_tributes").select("id,body,created_at").eq("memorial_id",id).eq("published",true).order("created_at"),sb.from("memorial_timeline_events").select("*").eq("memorial_id",id).order("event_date")]);
memories=await Promise.all((p.data||[]).map(async x=>{let u=x.image_url;if(x.storage_path){const z=await sb.storage.from("memorials").createSignedUrl(x.storage_path,3600);u=z.data?.signedUrl||u}return {...x,url:u}}));
galleryGrid.innerHTML=memories.map((x,i)=>x.url?'<button class="story-chapter" onclick="openReview('+i+')"><img src="'+esc(x.url)+'" alt="'+esc(x.caption||"Memory")+'"><p>'+esc(x.caption||"Memory")+'</p></button>':"").join("");
const events=(e.data||[]).map(x=>({date:x.event_date,title:x.title,description:x.description}));timelineList.innerHTML=events.length?events.map(x=>'<article class="story-event"><div class="story-date">'+esc(x.date)+'</div><div><h3>'+esc(x.title)+'</h3><p>'+esc(x.description||"")+'</p></div></article>').join(""):"<p>The family story is still being written.</p>";
voiceList.innerHTML=(s.data||[]).slice(0,8).map(x=>'<article class="story-voice"><h3>'+esc(x.title||"Family Story")+'</h3><p>'+esc(x.story||"")+'</p></article>').join("")||"<p>Family voices will appear here as they are published.</p>";
const chapters=[["Early Years","The beginning of the story."],["Family & Friends","The people who made life meaningful."],["Life & Work","The places, passions and accomplishments that shaped the journey."],["Legacy","The memories that continue forward."]];chapterGrid.innerHTML=chapters.map(x=>'<article class="story-chapter"><p class="eyebrow">'+esc(x[0])+'</p><p>'+esc(x[1])+'</p></article>').join("");
reviewImage.dataset.count=memories.length;
}
function openReview(i){reviewIndex=i;if(!memories[i])return;reviewImage.src=memories[i].url;reviewImage.alt=memories[i].caption||"Memory";reviewTitle.textContent=memorial.full_name||"";reviewCaption.textContent=memories[i].caption||"A moment preserved.";reviewModal.classList.add("open");reviewModal.setAttribute("aria-hidden","false")}
function next(){if(!memories.length)return;openReview((reviewIndex+1)%memories.length)}
reviewBtn.onclick=()=>openReview(0);nextReview.onclick=next;closeReview.onclick=()=>reviewModal.classList.remove("open");musicBtn.onclick=()=>{const a=document.getElementById("storyMusic");if(a.src){a.paused?a.play():a.pause()}else alert("Family music can be added to this Life Story from the Memorial Command Center.")};
document.querySelectorAll("[data-scroll]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"}));
load();