const sb=supabase.createClient(window.CROW_MEMORIALS.url,window.CROW_MEMORIALS.key);
const toast=document.getElementById('toast'),today=document.getElementById('today'),count=document.getElementById('candleCount');
let candles=Number(sessionStorage.getItem('memorialCandles')||0);
function showToast(msg){if(!toast)return;toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
if(today)today.textContent=new Intl.DateTimeFormat(undefined,{month:'long',day:'numeric',year:'numeric'}).format(new Date());
function render(){if(count)count.textContent=candles+' candle'+(candles===1?'':'s')+' lit in this session'}render();
document.getElementById('candleBtn')?.addEventListener('click',()=>{candles++;sessionStorage.setItem('memorialCandles',candles);render();showToast('🕯️ A candle has been lit in remembrance.')});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function loadFeatured(){const grid=document.querySelector('.cards');if(!grid)return;const {data,error}=await sb.from('memorials').select('id,slug,full_name,birth_date,passing_date,short_bio,is_celebrity,profession,portrait_url,created_at').eq('published',true).order('created_at',{ascending:true}).limit(3000);if(error||!data?.length){if(error)console.error('Memorial featured load:',error);return}const dayNumber=Math.floor(new Date(new Date().setHours(0,0,0,0)).getTime()/86400000),offset=(dayNumber*3)%data.length,featured=[0,1,2].map(i=>data[(offset+i)%data.length]);grid.innerHTML=featured.map(m=>{const u=m.portrait_url||'';return `<article class="card"><div class="photo${u?'':' photo-empty'}">${u?'<img src="'+esc(u)+'" alt="'+esc(m.full_name)+'" loading="lazy" decoding="async" onerror="this.onerror=null;this.parentElement.classList.add(\'photo-empty\');this.remove();">':''}</div><div><span class="tag">FEATURED CELEBRATION</span><h3>${esc(m.full_name)}</h3><p>${esc(m.short_bio||m.profession||'A life remembered and a story preserved.')}</p><a class="text-btn" href="celebration.html?slug=${encodeURIComponent(m.slug)}">Open celebration →</a></div></article>`}).join('');setTimeout(()=>location.reload(),Math.max(1000,new Date(new Date().setHours(24,0,0,0))-Date.now()+100))}
async function searchArchive(q){const term=q.trim();if(!term){showToast('Enter a name, story, or year to search.');return}if(/^\d{4}$/.test(term)){location.href='archives.html?deathYear='+encodeURIComponent(term);return}const safe=term.replace(/[(),.]/g,' ').replace(/\s+/g,' ').trim();const {data,error}=await sb.from('memorials').select('id,slug,full_name,birth_date,passing_date,short_bio,portrait_url').eq('published',true).or(`full_name.ilike.%${safe}%,short_bio.ilike.%${safe}%,known_for.ilike.%${safe}%`).limit(12);const results=document.getElementById('results');if(error){showToast(error.message);return}if(results)results.innerHTML=data?.length?data.map(m=>`<article class="archive-card"><span>MEMORIAL</span><h3>${esc(m.full_name)}</h3><p>${esc([m.birth_date,m.passing_date].filter(Boolean).join(' — '))}</p><a class="text-btn" href="celebration.html?slug=${encodeURIComponent(m.slug)}">Remember →</a></article>`).join(''):'<article class="archive-card"><h3>No memorials found</h3><p>Try another name or phrase.</p></article>'}
document.getElementById('searchBtn')?.addEventListener('click',()=>searchArchive(document.getElementById('search').value));document.getElementById('search')?.addEventListener('keydown',e=>{if(e.key==='Enter')searchArchive(e.target.value)});
document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>showToast('Sign in to continue with the CrowRules Memorials community tools.')));
async function loadOnThisDay(){const d=new Date(),md=`${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,{data,error}=await sb.from('memorials').select('slug,full_name,passing_date,short_bio').eq('published',true).not('passing_date','is',null).limit(3000);if(error){console.error('Memorial on-this-day load:',error);return}const matches=(data||[]).filter(m=>String(m.passing_date).slice(5,10)===md).slice(0,8),box=document.querySelector('.today');if(matches.length&&box)box.innerHTML=`<div><p class="eyebrow">TODAY WE REMEMBER</p><h2>On This Day</h2><p>${matches.map(m=>`<a href="celebration.html?slug=${encodeURIComponent(m.slug)}" style="display:block;color:#cda978;margin:8px 0">${esc(m.full_name)} · ${esc(m.passing_date)}</a>`).join('')}</p></div><div class="date">${today?.textContent||''}</div>`}
async function loadStatistics(){const ids=['statMemorials','statCelebrities','statFamily','statPortraits','statYears'],els=ids.map(id=>document.getElementById(id));if(!els.some(Boolean))return;const {data,error}=await sb.from('memorials').select('id,is_celebrity,portrait_url,passing_date').eq('published',true).limit(10000);if(error){console.error('Memorial statistics load:',error);els.forEach(el=>{if(el)el.textContent='—'});return}const rows=data||[],years=new Set(rows.map(m=>String(m.passing_date||'').slice(0,4)).filter(y=>/^\d{4}$/.test(y))),values=[rows.length,rows.filter(m=>m.is_celebrity===true).length,rows.filter(m=>m.is_celebrity!==true).length,rows.filter(m=>typeof m.portrait_url==='string'&&m.portrait_url.trim()).length,years.size];els.forEach((el,i)=>{if(el)el.textContent=values[i].toLocaleString()})}
loadFeatured();loadOnThisDay();loadStatistics();
