(() => {
const sb=supabase.createClient(window.CROW_MEMORIALS.url,window.CROW_MEMORIALS.key);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>d?new Intl.DateTimeFormat(undefined,{year:'numeric',month:'long',day:'numeric'}).format(new Date(d+'T00:00:00')):'';
async function renderCards(data,grid){
 const images=new Map();
 grid.innerHTML=data?.length?data.map(m=>{const fallback=m.portrait_url||'';return '<article class="page-card">'+(fallback?'<div class="photo" style="background-image:url(\''+esc(fallback)+'\')" role="img" aria-label="'+esc(m.full_name)+'"></div>':'<div class="photo photo-empty" aria-hidden="true"></div>')+'<div class="body"><span class="meta">'+(m.is_celebrity?'PUBLIC LIFE':'CELEBRATION')+'</span><h2>'+esc(m.full_name)+'</h2><p>'+esc([fmt(m.birth_date),fmt(m.passing_date)].filter(Boolean).join(' — '))+'</p><p>'+esc(m.short_bio||m.profession||m.memorial_message||'A life remembered and a story preserved.')+'</p><a class="text-btn" href="celebration.html?slug='+encodeURIComponent(m.slug)+'">Open celebration →</a></div></article>'}).join(''):'<div class="empty">No memorials are available yet.</div>';
}
async function celebrations(){
 const grid=document.getElementById('pageGrid'),status=document.getElementById('status');if(!grid)return;
 let q=sb.from('memorials').select('id,slug,full_name,birth_date,passing_date,short_bio,memorial_message,is_celebrity,profession,portrait_url').eq('published',true).order('created_at',{ascending:false}).limit(60);
 const type=document.getElementById('typeFilter')?.value;if(type==='celebrations')q=q.eq('is_celebrity',false);if(type==='public')q=q.eq('is_celebrity',true);
 const {data,error}=await q;if(error){status.textContent=error.message;return}await renderCards(data,grid);status.textContent=(data?.length||0)+' lives currently in the public archive.';
}
async function archives(){
 const grid=document.getElementById('pageGrid'),input=document.getElementById('archiveSearch'),status=document.getElementById('status'),countEl=document.getElementById('archiveCount'),yearPicker=document.getElementById('yearPicker'),yearSelect=document.getElementById('archiveYear');if(!grid)return;
 const filters=[...document.querySelectorAll('.archive-filter')];
 let view='recent';
 const loadYears=async()=>{const {data}=await sb.from('memorials').select('passing_date').eq('published',true).not('passing_date','is',null).order('passing_date',{ascending:false}).limit(3000);const years=[...new Set((data||[]).map(x=>String(x.passing_date).slice(0,4)).filter(y=>/^\\d{4}$/.test(y)))];if(yearSelect)yearSelect.innerHTML='<option value="">Select a year…</option>'+years.map(y=>'<option value="'+y+'">'+y+'</option>').join('')};
 const run=async()=>{const term=input.value.trim();let q=sb.from('memorials').select('id,slug,full_name,birth_date,passing_date,short_bio,profession,is_celebrity,known_for,portrait_url,created_at').eq('published',true).limit(60);
 if(view==='recent')q=q.order('created_at',{ascending:false});
 else if(view==='year'){const y=yearSelect?.value;if(!y){grid.innerHTML='<div class="empty"><h2>Pick a year</h2><p>Choose a year above to explore lives remembered from that year.</p></div>';status.textContent='Choose a year to begin.';if(countEl)countEl.textContent='Year archive';return}q=q.gte('passing_date',y+'-01-01').lt('passing_date',(Number(y)+1)+'-01-01').order('passing_date',{ascending:false})}
 else if(view==='public')q=q.eq('is_celebrity',true).order('full_name');
 else if(view==='family')q=q.eq('is_celebrity',false).order('full_name');
 else q=q.order('full_name');
 if(term)q=q.or('full_name.ilike.%'+term+'%,short_bio.ilike.%'+term+'%,known_for.ilike.%'+term+'%,profession.ilike.%'+term+'%');
 const {data,error}=await q;if(error){status.textContent='The archive could not be loaded.';grid.innerHTML='<div class="empty"><h2>Archive unavailable</h2><p>'+esc(error.message)+'</p><button class="text-btn" onclick="location.reload()">Retry</button></div>';if(countEl)countEl.textContent='Unable to load';return}
 await renderCards(data,grid);const total=data?.length||0;const labels={recent:'Recently added',year:'Year archive',public:'Public lives',family:'Family lives',all:'All archives'};status.textContent=(labels[view]||'Archive')+(term?' matching “'+esc(term)+'”.':'.');if(countEl)countEl.textContent=total.toLocaleString()+' memorials shown.';
 };
 filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));btn.classList.add('active');view=btn.dataset.view;yearPicker.hidden=view!=='year';run()}));
 yearSelect?.addEventListener('change',run);
 document.getElementById('searchBtn')?.addEventListener('click',run);input?.addEventListener('keydown',e=>e.key==='Enter'&&run());
 await loadYears();run();
}
async function onThisDay(){
 const grid=document.getElementById('pageGrid');if(!grid)return;const now=new Date(),md=String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');const {data,error}=await sb.from('memorials').select('id,slug,full_name,birth_date,passing_date,short_bio,profession,is_celebrity,portrait_url').eq('published',true).like('passing_date','%-'+md).order('passing_date',{ascending:false}).limit(60);if(error){grid.innerHTML='<div class="empty">'+esc(error.message)+'</div>';return}await renderCards(data,grid);document.getElementById('todayLabel').textContent=new Intl.DateTimeFormat(undefined,{month:'long',day:'numeric'}).format(now);
}
async function tributes(){
 const grid=document.getElementById('tributeGrid');if(!grid)return;const {data,error}=await sb.from('memorial_tributes').select('id,memorial_id,author_name,message,created_at').eq('published',true).order('created_at',{ascending:false}).limit(80);if(error){grid.innerHTML='<div class="empty">'+esc(error.message)+'</div>';return}
 const ids=[...new Set((data||[]).map(x=>x.memorial_id))];let memorials=[];if(ids.length){const r=await sb.from('memorials').select('id,slug,full_name').in('id',ids);memorials=r.data||[]}const map=new Map(memorials.map(m=>[m.id,m]));grid.innerHTML=data?.length?data.map(t=>{const m=map.get(t.memorial_id)||{};return '<article class="tribute"><blockquote>“'+esc(t.message)+'”</blockquote><div class="by">'+esc(t.author_name||'A friend or loved one')+' · remembering <a href="celebration.html?slug='+encodeURIComponent(m.slug||'')+'" style="color:var(--gold)">'+esc(m.full_name||'a life')+'</a></div></article>'}).join(''):'<div class="empty">No published tributes yet. Be the first to leave a remembrance.</div>';
}
async function stories(){const grid=document.getElementById('storyGrid'),status=document.getElementById('storyStatus'),input=document.getElementById('storySearch');if(!grid)return;const run=async()=>{const term=input.value.trim();let q=sb.from('memorial_stories').select('id,memorial_id,title,story,created_at').eq('published',true).order('created_at',{ascending:false}).limit(60);if(term)q=q.ilike('story','%'+term+'%');const {data,error}=await q;if(error){status.textContent=error.message;return}const ids=[...new Set((data||[]).map(x=>x.memorial_id))];let ms=[];if(ids.length){const r=await sb.from('memorials').select('id,slug,full_name,short_bio,is_celebrity,profession,portrait_url').in('id',ids).eq('published',true);ms=r.data||[]}const map=new Map(ms.map(m=>[m.id,m]));const rows=(data||[]).filter(x=>map.has(x.memorial_id));grid.innerHTML=rows.length?rows.map(x=>{const m=map.get(x.memorial_id),fallback=m.portrait_url||'';return '<article class="page-card">'+(fallback?'<div class="photo" style="background-image:url(\''+esc(im?im.url:fallback)+'\')" role="img" aria-label="'+esc(im?.alt||m.full_name)+'"></div>':'<div class="photo photo-empty" aria-hidden="true"></div>')+'<div class="body"><span class="meta">STORY · '+(m.is_celebrity?'PUBLIC LIFE':'FAMILY LIFE')+'</span><h2>'+esc(x.title||('A Story About '+m.full_name))+'</h2><p><strong>'+esc(m.full_name)+'</strong></p><p>'+esc((x.story||m.short_bio||m.profession||'').slice(0,300))+'</p><a class="text-btn" href="life-story.html?slug='+encodeURIComponent(m.slug)+'">Enter Life Story →</a></div></article>'}).join(''):'<div class="empty">No published stories matched your search.</div>';status.textContent=rows.length+' stories found.'};document.getElementById('storySearchBtn')?.addEventListener('click',run);input?.addEventListener('keydown',e=>e.key==='Enter'&&run());run()}
const page=document.body.dataset.page;if(page==='celebrations'){celebrations();document.getElementById('typeFilter')?.addEventListener('change',celebrations)}if(page==='archives')archives();if(page==='stories')stories();if(page==='onthisday')onThisDay();if(page==='tributes')tributes();
})();