const sb=supabase.createClient(window.CROW_MEMORIALS.url,window.CROW_MEMORIALS.key);
const mid=new URLSearchParams(location.search).get("memorial_id");let role=null;
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
async function boot(){const {data:{user}}=await sb.auth.getUser();if(!user){location.href="https://crowrulesentertainment-oss.github.io/crowspace/login.html?return=memorial-space";return}
const {data:access}=await sb.from("memorial_managers").select("role,status").eq("memorial_id",mid).eq("user_id",user.id).eq("status","active").maybeSingle();
if(access)role=access.role;else{const {data:c}=await sb.from("memorial_contributors").select("role,status").eq("memorial_id",mid).eq("user_id",user.id).eq("status","active").maybeSingle();if(c)role=c.role}
if(!role){document.body.innerHTML='<main><section class="section"><article class="archive-card"><h2>Private Memorial Space</h2><p>You do not have access to this Memorial Space.</p></article></section></main>';return}
const {data:m}=await sb.from("memorials").select("id,full_name,birth_date,passing_date,short_bio,portrait_url").eq("id",mid).single();
hero.innerHTML='<article class="archive-card"><span>PRIVATE FAMILY SPACE · '+esc(role.toUpperCase())+'</span><h1>'+esc(m.full_name)+'</h1><p>'+esc(m.short_bio||"A place for family memories, stories and tributes.")+'</p><div class="actions"><a class="btn" href="celebration.html?slug='+encodeURIComponent(m.slug||"")+'">View Public Celebration</a>'+(role==="owner"?'<a class="btn primary" href="family-manage.html?memorial_id='+mid+'">Family Settings</a>':'')+'</div></article>';
await loadOverview();document.querySelectorAll("#tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadTab(b.dataset.tab)});}
async function loadOverview(){const qs=await Promise.all(["memorial_photos","memorial_stories","memorial_tributes"].map(t=>sb.from(t).select("id,review_status,published").eq("memorial_id",mid)));stats.innerHTML=qs.map((r,i)=>'<article class="archive-card"><span>'+["PHOTOS","STORIES","TRIBUTES"][i]+'</span><h2>'+((r.data||[]).length)+'</h2><p>Family content</p></article>').join("");loadTab("overview")}
async function loadTab(tab){if(tab==="overview"){panel.innerHTML='<article class="archive-card"><h3>Your Family Memorial Space</h3><p>Use this private workspace to preserve memories together. Pending family content stays private until approved.</p></article>';return}
let table=tab==="photos"?"memorial_photos":tab==="stories"?"memorial_stories":"memorial_tributes";if(tab==="activity"){const {data,error}=await sb.from("memorial_activity_log").select("action,entity_type,created_at,actor_user_id").eq("memorial_id",mid).order("created_at",{ascending:false}).limit(50);panel.innerHTML=error?'<article class="archive-card"><p>'+esc(error.message)+'</p></article>':(data||[]).map(x=>'<article class="archive-card"><span>'+esc(x.action)+'</span><p>'+esc(x.entity_type)+' · '+new Date(x.created_at).toLocaleString()+'</p></article>').join("")||'<article class="archive-card"><p>No activity yet.</p></article>';return}
const {data,error}=await sb.from(table).select("*").eq("memorial_id",mid).order("created_at",{ascending:false});if(error){panel.innerHTML='<article class="archive-card"><p>'+esc(error.message)+'</p></article>';return}
panel.innerHTML=(data||[]).map(x=>'<article class="archive-card"><span>'+esc(x.review_status||"CONTENT")+'</span><h3>'+esc(x.title||x.caption||x.author_name||"Memory")+'</h3><p>'+esc(x.story||x.message||"")+'</p><small>'+esc(x.published?"Published":"Private / pending review")+'</small></article>').join("")||'<article class="archive-card"><h3>No content yet</h3><p>Family memories will appear here.</p></article>'}
boot();