const CROW_MEMORIALS_SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";
const CROW_MEMORIALS_SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
window.CROW_MEMORIALS={url:CROW_MEMORIALS_SUPABASE_URL,key:CROW_MEMORIALS_SUPABASE_KEY};